# -*- coding: utf-8 -*-
from json import *
from collections import OrderedDict

patterns = OrderedDict()

patterns["Patterns"] = {
    0: {
			"$": ["$&"],  # use unmodified
            "eillir$": ["eiller"],
            "indre$": ["ignre"],
            "cre$": ["qure"],
            "udre$": ["lvre","usre","ulre"],
            "prendre$": ["prenre"],
            "rire$": ["rivire","rivre"],
            "faire$": ["fere","fire"],
            "boire$": ["bre","buvre"],
            "vivre$": ["vécoir"],
            "naître$": ["naquir"],
            "(?<x>.)ître$|(?<x>e)ttre": ["re","${x}re", "${x}issre"],
            "vouloir$": ["voulre","voudre"],
            "oir$": ["re"],
            "voir$": ["verre"],
            "cevoir$": ["çoir"],
            "valoir$": ["vaudre"],
            "savoir$": ["sure","saure","sachre"],
            "pouvoir$": ["pourre", "pure"],
            "devoir$": ["dure"],
            "mouvoir": ["mure"],
            "ourir$": ["ourre","ourure"]
	},
    1: {
        # plurals
        "^.+(?<!s|x|z|eau|eu|al)$":  # ^ start of the string, .+ any # of chars, negative lookbehind
            ["$&s",
             "$&ai", "$&as", "$&a", "$&ons", "$&ez", "$&ont",  # futur simple
             "$&ais", "$&ait", "$&ions", "$&iez","$&aient"],  # conditionnel present
        "eau$": ["eaux"],
        "eu$": ["eux"],
        "al$": ["aux"],
        # verb group 1
        "er$": ["e","es","ons","ez","ent",
                "ais","ait","ions","iez","aient",
                "é",
                "ai", "as", "a","âmes","âtes","èrent",
                "asse","asses","ât","assions","assiez","assent",
                "ant",
                "ère","ères"], # fem adjective
        # fem adjective
        "$": ["e", "es"],
        "eux$": ["euse","euses"],
        "f$": ["ve","ves"],
        "t$": ["tte","ttes"],
        "l$": ["lle","lles"],
        "n$": ["nne","nnes"],
        # verb group 3
        "ir$": ["is","it","issons","issez","issent",  # verb group 2
                "issais","issait","issions","issiez","issaient",  # verb group 2
                "i","ie","ies",  # verb group 2
                "îmes","îtes","irent",  # verb group 2
                "isse","isses",  # verb group 2
                "ît",  # verb group 2
                "issant",  # verb group 2
                "e","es","ons","ez","ent", "s", "t",
                "ais","ait","ions","iez","aient",
                "ant"],
        "(?<letter>[tv])enir$": ["${letter}iens","${letter}ient","${letter}enons","${letter}enez","${letter}iennent",
                   "${letter}enais","${letter}enait", "${letter}enions","${letter}eniez","${letter}enaient",
                   "${letter}enu", "${letter}enue","${letter}enus","${letter}enues",
                   "${letter}ins","${letter}int","${letter}înmes","${letter}întes","${letter}inrent",
                   "${letter}iendrai","${letter}iendras","${letter}iendra","${letter}iendrons","${letter}iendrez","${letter}iendront",
                   "${letter}ienne","${letter}iennes",
                   "${letter}insse","${letter}insses","${letter}înt","${letter}inssions","${letter}inssiez","${letter}inssent",
                   "${letter}iendrais","${letter}iendrait","${letter}iendrions","${letter}iendriez","${letter}iendraient"
                   ],
        "érir$": ["iers","iert","érons","érez","ièrent",
                         "is","ise","ises",
                         "it","îmes","îtes","irent",
                         "errai","erras","erra","errons","errez","erront",
                         "uière","ières","ière",
                         "isse","isses","ît","issions","issiez","issent",
                         "errais","errait","errions","erriez","erraient"],
        "tir$|mir$|vir$": ["s","t","tons","tez","tent"],
        "uvrir$": ["uvert","uverte","uverts","uvertes"],
        "illir$": ["s","t"],
        "vêtir$": ["vêts","vêt","vêtons","vêtez","vêtent",
                   "vêtu","vêtue","vêtus","vêtues"],
        "mourir$": ["meurs","meurt","meurent",
                    "mort","morte","morts","mortes",
                    "meure","meures"],
        "fuir$": ["fuyons","fuyez","fuient",
                  "fuyais","fuyait","fuyions","fuyiez","fuyaient",
                  "fuyant"],
        "oir$": ["oyons","oyez","oient","ons","ez","ent",
                 "oyant","u","ue","us","ues",
                 "oyais","oyait","oyions","oyiez","oyaient",
                 "ut","ûmes","ûtes","urent","ût",
                 "usse","usses","ussions","ussiez","ussent"],
        "ouvoir$": ["euvent","eut"],
        "cevoir$": ["çoivent", "çoive", "çoives", ""],
        "vouloir": ["veux","veut","veulent","veuille","veuilles","veuillent","veuillez"],
        "valoir$": ["vaux","vaille","vailles","vaillent"],
        "pouvoir$": ["peux"],
        "mouvoir": ["meuve","meuves","mû"],
        "savoir$": ["sais","sait"],
        "devoir": ["dois", "doit","doivent","doive","doives","dû"],
        "eoir$": ["ois","oit","oyons","oyez","oient",
                  "oyant","is","ise","ises",
                  "oyais","oyait","oyions","oyiez","oyaient",
                  "it","îmes","îtes","irent",
                  "oirai","oiras","oira","oirons","oirez","oiront",
                  "oirais","oirait","oirions","oiriez","oiraient",
                  "oie","oies",
                  "isse","isses","ît","issions","issiez","issent"],
        "re$": ["ant","","e","s","es",
                "u","ue","us","ues",
                "t","ons","ez","ent",
                "is","it","îmes","îtes","irent",
                "isse","isses","ît","issions","issiez","issent",
                "ais","ait","ions","iez","aient",
                "rai","ras","ra","rons","rez","ront",
                "rais","rait","rions","riez","raient"],
        "ure$": ["ûmes","ûtes","urent",
                 "usse","usses","ût","ussions","ussiez","ussent"],
        "ore$": ["ut","ôt","osent",
                 "ose","oses","osions","osiez","osant"],
        "dre$": ["s","t","d","ons","ez","ent",
                 "de","des"],
        "prendre$": ["pris","prise","prises",
                     "prit","prîtes","prirent",
                     "prisse","prisses","prît","prissions","prissiez","prissent",
                     "prenne","prennes","prennent","prîmes"],
        "indre$": ["int","inte","ints","intes"],
        "udre$": ["ute","utes",
                  "ulut","ulûmes","ulûtes","ulurent",
                  "ulusse","ulusses","ulût","ulussions","ulussiez","ulussent"],
        "tre$": ["s","t","",
                 "te","tes"],
        "vre$": ["s","t",
                 "vi","vie","vies"],
        "ire$": ["is","it","îmes","îtes","irent",
                 "yons","isons","yez","isez","ient","isent",
                 "isant","ite","its","ites",
                 "isais","isait","isions","isiez","isaient",
                 "yais","yait","yions","yiez","yaient",
                 "ise","ises",
                 "ie","ies",
                 "yant",
                 "isse","isses","ît","issions","issiez","issent"],
        "dire$": ["dites"],
        "lire$": ["lut","lûmes","lûtes","lurent",
                  "lusse","lusses","lût","lussions","lussiez","lussent"],
        "uire$": ["uisis","uisit","uisîmes","uisîtes","uisirent",
                  "uisisse","uisisses","uisît","uisissions","uisissiez","uisissent"],
        "crire$": ["crivons","crivez","crivent"],
        "boire$": ["boivent",
                   "bûmes","bûtes","burent",
                   "boive","boives","boive","boivent",
                   "busse","busses","bût","bussions","bussiez","bussent"],
        "aire$": ["aisons","aites","ont","aît",
                  "u",
                  "usse","usses","ût","ussions","ussiez","ussent",
                  "ut","ûmes","ûtes","urent"],
        "faire$": ["fasse","fasses","fassions","fassiez","fassent"],
        "(?<x>.)ître$": ["ut","ûmes","ûtes","urent",
                         "usse","usses","ût","ussions","ussiez","ussent"],
        "naître$": ["né","nés","née","nées"],
        "croître$": ["crû",
                     "crûrent",
                     "crûsse","crûsses","crûssent",
                     "crû","crûe","crûs","crûes",
                     "crûssions","crûssiez"],
        "mettre$": ["mise","mises"],
        }
    }
patterns["Prefixes"] = ["j'", "l'", "n'", "m'", "t'"]


with open("French.json", mode='w', encoding='utf-8') as file:
            file.write(dumps(patterns))